<?php

/**
 * @file
 * Defines a simple geolocation field type.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function geolocation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.geolocation' :
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>'
        . t('The Geolocation module allows you to create fields that contain geographical locations.
          See the <a href="!field">Field module help</a> and the <a href="!field_ui">Field UI help</a>
          pages for general information on fields and how to create and manage them.',
          [
            '!field' => \Drupal::url('help.page', ['name' => 'field']),
            '!field_ui' => \Drupal::url('help.page', ['name' => 'field_ui'])
          ]
        )
        . '</p>';
      return $output;
      break;
  }
}

/**
 * Implements hook_theme().
 */
function geolocation_theme() {
  return [
    'geolocation_latlng_formatter' => [
      'variables' => [
        'lat' => NULL,
        'lng' => NULL
      ],
      'template' => 'geolocation-latlng-formatter',
    ],
    'geolocation_common_map_display' => [
      'variables' => [
        'centre' => NULL,
        'locations' => NULL,
        'id' => NULL,
      ]
    ],
    'geolocation_common_map_location' => [
      'variables' => [
        'content' => NULL,
        'title' => NULL,
        'position' => NULL,
      ]
    ],
  ];
}
